name: Maven Deploy Artifact

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  deploy:
    uses: empayre/java-workflow/.github/workflows/maven-swag-deploy.yml@master
    with:
      run-script-name: build
    secrets:
      mm-webhook-url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
      github-token: ${{ secrets.GITHUB_TOKEN }}